'use strict';

const fs = require('fs');
const path = require('path');

function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'"'"'`)}'`;
}

function writePrivate(file, content, fsImpl = fs) {
  fsImpl.mkdirSync(path.dirname(file), { recursive: true });
  fsImpl.writeFileSync(file, content, { encoding: 'utf8', mode: 0o600 });
  try { fsImpl.chmodSync(file, 0o600); } catch (_) {}
}

function prepareZshRuntime({ userDataDir, originalZdotdir, hookFile, fsImpl = fs }) {
  const runtimeDir = path.join(userDataDir, 'shell-integration', 'zsh');
  const original = originalZdotdir || '';
  const sourceOriginal = (name) => [
    `# Generated by Cupertino Terminal. Do not edit.`,
    `_cupertino_runtime_zdotdir="$ZDOTDIR"`,
    `_cupertino_original_zdotdir=${shellQuote(original)}`,
    `ZDOTDIR="$_cupertino_original_zdotdir"`,
    `if [[ -r "$_cupertino_original_zdotdir/${name}" ]]; then`,
    `  source "$_cupertino_original_zdotdir/${name}"`,
    'fi',
    `ZDOTDIR="$_cupertino_runtime_zdotdir"`,
    'unset _cupertino_original_zdotdir _cupertino_runtime_zdotdir',
    '',
  ].join('\n');

  for (const name of ['.zshenv', '.zprofile', '.zlogin', '.zlogout']) {
    writePrivate(path.join(runtimeDir, name), sourceOriginal(name), fsImpl);
  }
  const zshrc = sourceOriginal('.zshrc') + [
    '# Keep history outside the generated/runtime ZDOTDIR and read-only app bundles.',
    `if [[ -z "$HISTFILE" || "$HISTFILE" == "$ZDOTDIR/"* ]]; then`,
    `  HISTFILE=${shellQuote(path.posix.join(original.replace(/\\/g, '/'), '.zsh_history'))}`,
    'fi',
    `source ${shellQuote(hookFile)}`,
    '',
  ].join('\n');
  writePrivate(path.join(runtimeDir, '.zshrc'), zshrc, fsImpl);
  return runtimeDir;
}

function buildShellLaunch({ profile, cwd, platform, env = process.env, version, userDataDir, integrationDir }) {
  const launchEnv = { ...env, TERM_PROGRAM: 'Cupertino_Terminal', TERM_PROGRAM_VERSION: version };
  if (platform === 'darwin') {
    const delimiter = ':';
    const defaults = ['/opt/homebrew/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin'];
    const existing = String(launchEnv.PATH || '').split(delimiter).filter(Boolean);
    launchEnv.PATH = [...new Set([...defaults, ...existing])].join(delimiter);
  }
  if (profile.command === 'zsh') {
    const originalZdotdir = env.ZDOTDIR || env.HOME || require('os').homedir();
    launchEnv.CUPERTINO_ORIGINAL_ZDOTDIR = originalZdotdir;
    launchEnv.ZDOTDIR = prepareZshRuntime({
      userDataDir,
      originalZdotdir,
      hookFile: path.join(integrationDir, '.zshrc'),
    });
    return { args: [...profile.args], env: launchEnv };
  }
  if (profile.command === 'bash') return { args: ['--rcfile', path.join(integrationDir, 'bash.bash'), '-i'], env: launchEnv };
  if (profile.command === 'fish') return { args: ['-l', '-C', `source ${shellQuote(path.join(integrationDir, 'fish.fish'))}`], env: launchEnv };
  if (profile.command === 'powershell.exe' || profile.command === 'pwsh.exe') {
    return { args: ['-NoExit', '-File', path.join(integrationDir, 'powershell.ps1')], env: launchEnv };
  }
  if (profile.command === 'wsl.exe') return { args: ['--cd', cwd || '~'], env: launchEnv };
  return { args: [...profile.args], env: launchEnv };
}

module.exports = { shellQuote, prepareZshRuntime, buildShellLaunch };
